# Generated by Django 5.2 on 2025-05-02 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_remove_bill_user_bill_billing_address_and_more"),
        ("inventory", "0003_alter_category_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="bill",
            old_name="total_price",
            new_name="total_amount",
        ),
        migrations.RemoveField(
            model_name="bill",
            name="medicine",
        ),
        migrations.RemoveField(
            model_name="bill",
            name="packaging_type",
        ),
        migrations.RemoveField(
            model_name="bill",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="bill",
            name="unit_price",
        ),
        migrations.AlterField(
            model_name="bill",
            name="staff_user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="BillItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "packaging_type",
                    models.CharField(
                        choices=[
                            ("single", "Single"),
                            ("strip", "Strip"),
                            ("pack", "Pack"),
                            ("box", "Box"),
                        ],
                        max_length=10,
                    ),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="billing.bill",
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.medicine",
                    ),
                ),
            ],
        ),
    ]
