# Generated by Django 5.2 on 2025-05-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_rename_total_price_bill_total_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billitem",
            name="packaging_type",
            field=models.CharField(
                choices=[
                    ("single", "Single Unit"),
                    ("strip", "Strip"),
                    ("pack", "Pack"),
                    ("box", "Box"),
                ],
                max_length=10,
            ),
        ),
    ]
