# Generated by Django 5.2 on 2025-05-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_alter_billitem_packaging_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="invoice_number",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
