# Generated by Django 5.2 on 2025-04-29 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=50)),
                ('price_single', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_strip', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_pack', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_box', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('expiry_date', models.DateField()),
            ],
        ),
    ]
