# Generated by Django 5.2 on 2025-05-02 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="category",
            table="categories",
        ),
    ]
