# Generated by Django 5.2 on 2025-05-03 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_alter_category_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="stock_threshold",
            field=models.IntegerField(default=10),
        ),
    ]
